config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registration], controllers: {
    omniauth_callbacks: 'admins/omniauth_callbacks'
  }

  root 'clients#index'

  namespace :api do
    resources :clients, only: [:index, :show]
  end

  resources :clients

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  validates :email, format: { :with => /\A([^@\s]+)@(futureworkz.com)\Z/i }

  def self.find_for_google_oauth2(access_token)
    data = access_token.info
    Admin.where(email: data['email']).first
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  extend Enumerize

  default_scope -> { order(first_name: :asc, last_name: :asc, id: :desc) }

  scope :options, -> { pluck(:company_name, :id) }

  validates :first_name, :last_name, :email, :address, :company_name, :designation, presence: true
  validates :email, format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  enumerize :title, in: [:mr, :mrs, :ms, :dr, :mdm], default: :mr

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admins/omniauth_callbacks_controller.rb
class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    @admin = Admin.find_for_google_oauth2(google_authenticated_data)

    if @admin
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @admin, event: :authentication
    else
      flash[:alert] = 'You are not allowed to log in.'
      redirect_to root_path
    end
  end

  private
  def google_authenticated_data
    request.env['omniauth.auth']
  end
end

app/controllers/adminscontroller.rb
class AdminsController < ApplicationController; end

app/controllers/api/clients_controller.rb
class Api::ClientsController < ApplicationController
  USER_NAME = ENV['AUTHENTICATE_USER_NAME']
  PASSWORD = ENV['AUTHENTICATE_PASSWORD']

  before_action :authenticate

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(client_id)
  end

  protected
  def client_id
    params.require(:id)
  end

  def authenticate
    case request.format
    when Mime::JSON
      authenticate_or_request_with_http_basic do |user_name, password|
        user_name == USER_NAME && password == PASSWORD
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @clients = Client.paginate(page: page)
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_param)

    if @client.save
      redirect_to clients_path, notice: t('client.message.create_success')
    else
      flash[:alert] = t('client.message.create_failed')
      render :new
    end
  end

  def edit
    @client = Client.find(client_id)
  end

  def update
    @client = Client.find(client_id)

    if @client.update(client_param)
      redirect_to clients_path, notice: t('client.message.update_success')
    else
      flash[:alert] = t('client.message.update_failed')
      render :edit
    end
  end

  def destroy
    @client = Client.find(client_id)
    if @client.destroy
      redirect_to clients_path, notice: t('client.message.delete_success')
    else
      redirect_to clients_path, alert: t('client.message.delete_failed')
    end
  end

  protected
  def client_id
    params.require(:id)
  end

  def page
    params[:page]
  end

  def client_param
    params.require(:client).permit(:title, :first_name, :last_name, :email, :phone, :address, :company_name, :designation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_page_title(title)
    render partial: 'shared/breadcrumb', locals: { page_title: title }
  end

  def label_name(key)
    t("helpers.label.#{key}")
  end
end

app/helpers/list_helper.rb
module ListHelper
  def list_edit_button(resource)
    link_to 'Edit', list_action_path(resource, :edit), list_edit_button_options(resource)
  end

  def list_delete_button(resource)
    link_to 'Delete', list_action_path(resource, :delete), list_delete_button_options(resource)
  end

  def bootstrap_paginate(resources)
    will_paginate(resources, {renderer: BootstrapPagination::Rails, next_label: '&raquo;', previous_label: '&laquo;'})
  end

  def list_action_path(resource, action)
    if action == :edit
      path = "edit_#{resource_class(resource)}_path".to_sym
    elsif action == :delete
      path = "#{resource_class(resource)}_path".to_sym
    end

    send(path, resource.id)
  end

  def resource_class(resource)
    resource.class.to_s.downcase
  end

  def list_edit_button_options(resource)
    {class: 'list-edit-button', data: {test: "edit-#{resource_class(resource)}-#{resource.id}"}}
  end

  def list_delete_button_options(resource)
    {method: :delete, class: 'list-delete-button', data:{confirm: t("#{resource_class(resource)}.message.delete_confirmation"), test: "delete-#{resource_class(resource)}-#{resource.id}"}}
  end
end

app/views/clients/_form.haml
= bootstrap_form_for client do |f|
  = f.select :title, Client.title.options
  = f.text_field :first_name
  = f.text_field :last_name
  = f.email_field :email
  = f.text_field :phone
  = f.text_field :designation
  = f.text_area :address
  = f.text_field :company_name
  = f.submit 'Submit', class: 'btn-u'
  = link_to 'Back', clients_path, class: 'btn-u btn-u-default'

app/views/clients/edit.html.haml
= display_page_title('Edit client')

.container.content
  .col-md-6
    = render partial: 'clients/form', locals: {client: @client}

app/views/clients/index.html.haml
= display_page_title('Clients List')

.container.content
  %table.list-table
    %thead
      %tr
        %th= label_name('client.title')
        %th= label_name('client.first_name')
        %th= label_name('client.last_name')
        %th= label_name('client.designation')
        %th= label_name('client.email')
        %th= label_name('client.phone')
        %th= label_name('client.address')
        %th= label_name('client.company_name')
        %th= label_name('client.action')
    - @clients.each do |client|
      %tr
        %td= client.title.text
        %td= client.first_name
        %td= client.last_name
        %td= client.designation
        %td= client.email
        %td= client.phone
        %td= client.address
        %td= client.company_name
        %td
          = list_edit_button(client)
          = list_delete_button(client)


  .pagination
    = bootstrap_paginate(@clients)

app/views/clients/new.html.haml
= display_page_title('Add New Client')
.container.content
  .col-md-6
    = render partial: 'clients/form', locals: { client: @client }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title ClientAPI
    = stylesheet_link_tag    'application', media: 'all', data: { turbolinks_track: true }
    = javascript_include_tag 'application', data: { turbolinks_track: true }
    = csrf_meta_tags
  %body
    .wrapper.container-fluid
      .header.row
        .container
          .topbar
            .container
              %ul.loginbar.pull-right
                - if current_admin.present?
                  %li= "Welcome #{current_admin.email}"
                  %li.topbar-devider
                  %li= link_to 'Logout', destroy_admin_session_path, method: :delete
                - else
                  %li= link_to 'Sign in with Google', admin_omniauth_authorize_path(:google_oauth2)
          .navbar.navbar-default
            .navbar-header
              = link_to(image_tag('neember-logo.png', height: 40), root_path)
            = render_navigation expand_all: true, renderer: :bootstrap
      .main-body
        .container
          - if flash_messages.present?
            .flash-messages= flash_messages
        = yield

app/views/shared/_breadcrumb.haml
.breadcrumbs.row
  .container
    %h1.pull-left= page_title